{% set name = "chinese-whispers" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/chinese_whispers-{{ version }}.tar.gz
  sha256: ed63521dec01210c6f0c3e8a6e234aa2dfd6b1fac47872b1ef285bd1b1723704

build:
  entry_points:
    - chinese-whispers = chinese_whispers.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - networkx >=2.1,<4.0

test:
  imports:
    - chinese_whispers
  commands:
    - pip check
    - chinese-whispers --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nlpub/chinese-whispers-python
  summary: An implementation of the Chinese Whispers clustering algorithm.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dustalov
