{% set name = "chinese-whispers" %}
{% set version = "0.8.2.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/chinese_whispers-{{ version }}.tar.gz
  sha256: ed4a5bc364ff44dc176be2616ed1f90acd4a2997df360b398751b08b8c948acf

build:
  entry_points:
    - chinese-whispers = chinese_whispers.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - networkx >=2.1,<4.0

test:
  imports:
    - chinese_whispers
  commands:
    - pip check
    - chinese-whispers --help
  requires:
    - pip

about:
  home: https://github.com/nlpub/chinese-whispers-python
  summary: An implementation of the Chinese Whispers clustering algorithm.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dustalov
